spring:
  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
app:
  name: cineProject
  version: 0.0.1
  jwt:
    key: 703373357638792F423F4528482B4D6251655468576D5A7134743777397A2443